### ISSUE TITLE
Remove TestNotePasser and TestPasswordAccountLoader from the suite

### ISSUE THREAD

**Issue by quinnshultz** [quinnshultz/opal#13]
When tests are run with Gradle, it does not skip TestNotePasser and TestPasswordAccountLoader, which have been deleted. The following error is produced for each class:

junit.framework.AssertionFailedError: No tests found in com.billsbackyardbees.opal.test.unit.TestNotePasser
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.TestCase.fail(TestCase.java:227)
	at junit.framework.TestSuite$1.runTest(TestSuite.java:97)

**Comment by quinnshultz** [comment]
This is a misreported bug. My build directory was out of sync and new users will not face this issue.
